services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - salinstudio:/var/lib/postgresql
  server:
    image: fenroe/salinstudio-server:latest
    env_file: .env
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
  admin:
    image: fenroe/salinstudio-admin:latest
    env_file: .env
    pull_policy: always
    ports:
      - 334:3000
  web:
    image: fenroe/salinstudio-web:latest
    env_file: .env
    pull_policy: always
    ports:
      - 333:3000
volumes:
  salinstudio:
