services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - salinstudio:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  server:
    image: fenroe/salinstudio-server:latest
    env_file: .env
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
  admin:
    image: fenroe/salinstudio-admin:latest
    env_file: .env
    pull_policy: always
    ports:
      - 334:3000
  web:
    image: fenroe/salinstudio-web:latest
    env_file: .env
    pull_policy: always
  proxy:
    image: nginx:alpine
    ports:
      - 333:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      web:
        condition: service_started
      admin:
        condition: service_started
      server:
        condition: service_started

volumes:
  salinstudio:
