// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Image struct {
	ID             uuid.UUID
	ImageUrlFull   string
	ImageUrlMobile string
	ImageUrlThumb  string
	Index          int32
	Category       string
	TitleEn        string
	TitleFi        string
	CreatedAt      time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	CreatedAt      time.Time
}
